"""Dual-stream generation under intervention, resumable in chunks.

Sequencing invariant (pre-registered, unit-tested): the clean pass's top-10 next-token ids
for position t are computed BEFORE the intervened pass's band hooks fire at position t —
during prefill (clean prefill first, whole prompt) and at every decode step (clean forward
for the new token first). Both streams consume the SAME sampled tokens; only the intervened
stream's logits choose them.

Resumability: generate() accepts prefix_ids (tokens generated by a previous, interrupted
call) and gen_state (the sampler's saved generator state); generate_resumable() wraps this
with periodic persistence so a SIGKILL costs at most one chunk. The prompt+prefix is
re-prefilled through both streams, which replays the original exemption sets
deterministically. Caveat, documented for the report: GPU prefill vs. incremental decode
can differ in the last floating-point bits, so a resumed generation may diverge from its
uninterrupted counterpart at the resume boundary. Chunking is used uniformly for every
condition, so this cannot bias between-condition comparisons.

Sampling is done on CPU with a seeded generator (temperature -> top-k -> top-p), identical
code path for clean and intervened runs so decoding differences cannot confound conditions.
"""

from dataclasses import dataclass, field

import torch
from transformers import DynamicCache

from jspace.core import Setup, SAMPLING, K_CLEAN_EXEMPT
from jspace.ablation import JSpaceAblator

CHUNK = 64  # tokens between persistence points in generate_resumable


@dataclass
class GenResult:
    text: str                 # decoded from the full stream (prefix + new)
    token_ids: list[int]      # full stream: prefix_ids + newly generated
    n_new: int                # newly generated THIS call
    hit_cap: bool
    stopped: bool             # ended on EOS
    norm_log: dict[int, float] = field(default_factory=dict)
    gen_state: list[int] | None = None  # sampler state for resumption


def _eos_ids(tok) -> set[int]:
    # Qwen3 registers two EOS ids: <|im_end|> (151645) and <|endoftext|> (151643).
    ids = {tok.eos_token_id, tok.convert_tokens_to_ids("<|im_end|>"),
           tok.convert_tokens_to_ids("<|endoftext|>")}
    return {t for t in ids if t is not None}


def _sample(logits: torch.Tensor, gen: torch.Generator | None) -> int:
    if gen is None:  # greedy (used only by calibration controls, never the main grid)
        return int(logits.argmax().item())
    logits = logits.float().cpu() / SAMPLING["temperature"]
    topk = logits.topk(SAMPLING["top_k"])
    probs = torch.softmax(topk.values, dim=-1)
    sorted_probs, order = probs.sort(descending=True)
    keep = sorted_probs.cumsum(0) - sorted_probs < SAMPLING["top_p"]
    keep[0] = True
    idx = torch.multinomial(sorted_probs * keep, 1, generator=gen)
    return topk.indices[order[idx]].item()


@torch.no_grad()
def generate(setup: Setup, prompt: str, max_new_tokens: int, seed: int,
             ablator: JSpaceAblator | None = None, greedy: bool = False,
             prefix_ids: list[int] | None = None,
             gen_state: list[int] | None = None,
             stop_after: int | None = None) -> GenResult:
    """Generate up to max_new_tokens total new tokens (counting prefix_ids), or at most
    stop_after new tokens this call."""
    tok, hf = setup.tok, setup.hf
    prefix_ids = list(prefix_ids or [])
    prompt_ids = tok(prompt, return_tensors="pt").input_ids[0].tolist()
    ids = torch.tensor([prompt_ids + prefix_ids], device=setup.device)
    if greedy:
        gen = None
    else:
        gen = torch.Generator().manual_seed(seed)
        if gen_state is not None:
            gen.set_state(torch.tensor(gen_state, dtype=torch.uint8))
    eos = _eos_ids(tok)
    budget = max_new_tokens - len(prefix_ids)
    if stop_after is not None:
        budget = min(budget, stop_after)

    new_ids: list[int] = []
    stopped = False
    if budget > 0 and ablator is None:
        cache = DynamicCache()
        out = hf(ids, past_key_values=cache, use_cache=True)
        next_id = _sample(out.logits[0, -1], gen)
        while True:
            new_ids.append(next_id)
            if next_id in eos or len(new_ids) >= budget:
                break
            step = torch.tensor([[next_id]], device=setup.device)
            out = hf(step, past_key_values=cache, use_cache=True)
            next_id = _sample(out.logits[0, -1], gen)
        stopped = new_ids[-1] in eos
    elif budget > 0:
        main_cache, clean_cache = DynamicCache(), DynamicCache()
        try:
            # Clean prefill first (hooks silent): exemptions for every position of
            # prompt + prefix — a deterministic replay of the original sets.
            ablator.enabled = False
            out_c = hf(ids, past_key_values=clean_cache, use_cache=True)
            ablator.exempt_ids = out_c.logits[0].topk(K_CLEAN_EXEMPT, dim=-1).indices
            ablator.enabled = True
            out = hf(ids, past_key_values=main_cache, use_cache=True)
            ablator.enabled = False
            next_id = _sample(out.logits[0, -1], gen)
            while True:
                new_ids.append(next_id)
                if next_id in eos or len(new_ids) >= budget:
                    break
                step = torch.tensor([[next_id]], device=setup.device)
                # Clean stream consumes the token first -> exemptions for this position.
                out_c = hf(step, past_key_values=clean_cache, use_cache=True)
                ablator.exempt_ids = out_c.logits[0].topk(K_CLEAN_EXEMPT, dim=-1).indices
                ablator.enabled = True
                out = hf(step, past_key_values=main_cache, use_cache=True)
                ablator.enabled = False
                next_id = _sample(out.logits[0, -1], gen)
            stopped = new_ids[-1] in eos
        finally:
            ablator.enabled = False  # never leak an enabled hook to a later forward

    full = prefix_ids + new_ids
    return GenResult(
        text=tok.decode(full, skip_special_tokens=True),
        token_ids=full,
        n_new=len(new_ids),
        hit_cap=len(full) >= max_new_tokens and not stopped,
        stopped=stopped,
        norm_log=ablator.pop_norm_summary() if ablator is not None else {},
        gen_state=None if gen is None else gen.get_state().tolist(),
    )


def generate_resumable(setup: Setup, prompt: str, max_new_tokens: int, seed: int,
                       ablator: JSpaceAblator | None, state: dict, save,
                       chunk: int = CHUNK) -> GenResult:
    """Chunked generation with persistence: state (a mutable dict owned by the caller)
    accumulates {"tokens", "gen_state", "done", "stopped", "norms", "n"}; save() is
    called after every chunk. A SIGKILL costs at most one chunk of work."""
    state.setdefault("tokens", [])
    state.setdefault("gen_state", None)
    state.setdefault("norms", {})
    state.setdefault("n", 0)
    while not state.get("done"):
        r = generate(setup, prompt, max_new_tokens, seed, ablator=ablator,
                     prefix_ids=state["tokens"], gen_state=state["gen_state"],
                     stop_after=chunk)
        state["tokens"] = r.token_ids
        state["gen_state"] = r.gen_state
        for l, v in r.norm_log.items():
            state["norms"][str(l)] = (state["norms"].get(str(l), 0.0) * state["n"]
                                      + v * r.n_new) / max(state["n"] + r.n_new, 1)
        state["n"] += r.n_new
        state["stopped"] = r.stopped
        state["done"] = r.stopped or len(state["tokens"]) >= max_new_tokens or r.n_new == 0
        save()
    toks = state["tokens"]
    return GenResult(
        text=setup.tok.decode(toks, skip_special_tokens=True),
        token_ids=toks,
        n_new=len(toks),
        hit_cap=len(toks) >= max_new_tokens and not state.get("stopped"),
        stopped=bool(state.get("stopped")),
        norm_log={int(l): v for l, v in state["norms"].items()},
    )
